export default {
  ADD_VIEW: 'ADD_VIEW',
  UPDATE_LAYOUT: 'UPDATE_LAYOUT',
  ADD_WIDGET: 'ADD_WIDGET',
  UPDATE_WIDGET: 'UPDATE_WIDGET',
  SET_PLACEHOLDER: 'SET_PLACEHOLDER',
  REMOVE_PLACEHOLDER: 'REMOVE_PLACEHOLDER'
};